image: "sigrlami/stack-build:latest"

before_script:
  - apt-get update && apt-get install -y xz-utils make openssh-client
  # add woraround to properly fetch packages as git repos
  - ssh-keygen -t rsa -C "ci@migamake.com" -f ~/.ssh/id_rsa
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  # prepare dependency cache for further reuse
  - export STACK_ROOT=`pwd`/.stack
  - stack new site simple-slick.hsfiles
  - cd site
  - stack setup --verbose
  - stack install --only-dependencies
  - stack build

build:
  cache:
    paths:
      - _cache
      - .stack
  script:
    - cd site
    - stack exec -- site
  except:
    - master

pages:
  cache:
    paths:
      - _cache
      - .stack
  script:
    - cd site
    - stack exec -- site
  artifacts:
    paths:
      - site/public
  only:
    - master
